# Generated by Django 5.0.6 on 2024-05-28 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HazardControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harzard', models.CharField(max_length=100)),
                ('risk', models.CharField(max_length=100)),
                ('control', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('taskName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_inittiator', to='take_five.employee')),
                ('hazard', models.ManyToManyField(to='take_five.hazardcontrol')),
                ('other_workers', models.ManyToManyField(null=True, related_name='task_members', to='take_five.employee')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_supervisor', to='take_five.employee')),
            ],
        ),
    ]
