# Generated by Django 5.0.6 on 2024-07-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_five', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardcontrol',
            old_name='harzard_description',
            new_name='hazard_description',
        ),
    ]
