# Generated by Django 5.0.6 on 2024-09-15 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_five', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['control_description']},
        ),
        migrations.AlterModelOptions(
            name='hazardcontrol',
            options={'ordering': ['hazard_description']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
