# Generated by Django 5.0.6 on 2024-06-26 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_five', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hazardcontrol',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='hazardcontrol',
            name='control',
        ),
        migrations.AddField(
            model_name='hazardcontrol',
            name='control',
            field=models.ManyToManyField(to='take_five.control'),
        ),
    ]
