# Generated by Django 5.0.6 on 2024-09-15 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_five', '0002_alter_control_options_alter_hazardcontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
