# Generated by Django 5.0.6 on 2024-07-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_five', '0002_rename_harzard_description_hazardcontrol_hazard_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hazard',
            new_name='hazard_control_list',
        ),
    ]
