# Generated by Django 5.0.6 on 2024-06-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_five', '0002_control_remove_hazardcontrol_risk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardcontrol',
            old_name='control',
            new_name='controls',
        ),
    ]
