# Generated by Django 5.0.6 on 2024-12-09 11:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearMiss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('department', models.CharField(max_length=255)),
                ('hazard_class', models.CharField(max_length=255)),
                ('unsafe_act', models.CharField(max_length=255)),
                ('near_miss_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='near_miss')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_by', to='employee.employee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
