# Generated by Django 5.0.6 on 2024-12-02 13:22

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('time_of_incident', models.TimeField()),
                ('date_of_incident', models.DateField()),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('statement', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='incidents_reports')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to='employee.employee')),
            ],
            options={
                'ordering': ['date_of_incident'],
            },
        ),
    ]
