# Generated by Django 5.0.6 on 2024-07-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('incident_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incident_Report',
            new_name='IncidentReport',
        ),
    ]
