# Generated by Django 5.0.6 on 2024-07-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_report', '0002_rename_incident_report_incidentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='time_of_incident',
            field=models.TimeField(),
        ),
    ]
