# Generated by Django 5.0.6 on 2024-09-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_report', '0003_alter_incidentreport_time_of_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['date_of_incident']},
        ),
    ]
