# Generated by Django 5.0.6 on 2024-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_report', '0004_alter_incidentreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='image',
            field=models.ImageField(null=True, upload_to='files/covers'),
        ),
    ]
